### ISSUE TITLE
윈도우 -Dspring 코드 

### ISSUE THREAD

**Issue by myway00** [PeerGroup-JavaSpringBoot/SpringBootStudy#44]
지금 chapter 6 을 듣고 있던 중, `Spring Boot Properties` 강의 30분 경에서
강사님이 써주신
```
java -jar -Dspring.profiles.active=local -jar build/libs/jpa-0.0.1-SNAPSHOT.jar
```
이 코드를 터미널에 치면 자꾸 클래스를 찾을 수 없다고 에러가 떴습니다.
이와 같은 사례가 있나 검색해보니깐
[https://stackoverflow.com/questions/46614338/issue-run-spring-boot-profiles-jar](https://stackoverflow.com/questions/46614338/issue-run-spring-boot-profiles-jar) 요론 스택오버플로우를 발견했어요~

이걸 참고해서 코드를 아래와 같이 수정한 뒤에

````
java -jar "-Dspring.profiles.active=local" -jar build/libs/jpa-0.0.1-SNAPSHOT.jar
````
실행을 하니깐 작동하더라구요 !
만약 저와 같은 에러가 일어나면 한번 시도해보시면 좋을 것 같아서 이슈에 남깁니다 ㅎㅎ
모두 열공하세요!

**Comment by hehahihang** [comment]
저도 같은 에러 발생했었는데 이슈 남겨주신거 확인하고 해결했습니다!
동윤님 감사합니다ㅎㅎ
