### ISSUE TITLE
@Enumerated - EnumType.STRING

### ISSUE THREAD

**Issue by yoon-youngjin** [PeerGroup-JavaSpringBoot/SpringBootStudy#83]
### `@Enumerated`을 이용할 때 반드시 EnumType은 String을 사용하자!

- `@Enumerated` 애너테이션에는 두 가지 EnumType이 존재
  - EnumType.ORDINAL: enum 순서 값을 DB에 저장
  - EnumType.STRING: enum 이름을 DB에 저장

```java
enum OrderStatus{
    READY, FINISH
        }
```

- 이와 같이 OrderStatus의 enum타입이 명시된 경우라고 가정하자.

```java
@Enumerated(EnumType.ORDINAL)
private OrderStatus orderstatus;
```

- EnumType.ORDINAL인 경우 DB에 READY는 1, FINISH는 2인 상태로 저장

```java
@Enumerated(EnumType.STRING)
private OrderStatus orderstatus;
```

- EnumType.STRING인 경우 DB에 READY, FINISH로 저장

- 만약 OrderStatus에 필드가 추가 된다면?

```java
enum OrderStatus{
    READY, DELIVERY,  FINISH
        }
```

- EnumType.ORDINAL인 경우에 기존 DB의 OrderStatus 속성값의 2는 DELEVERY가 되어 큰 문제가 발생
- **@Enumerated의 기본 값은 EnumType.ORDINAL이므로 반드시 EnumType.STRING으로 사용하자!**

**Comment by myway00** [comment]
> * EnumType.STRING인 경우 DB에 READY, FINISH로 저장
> * 만약 OrderStatus에 필드가 추가 된다면?
> 
> ```java
> enum OrderStatus{
>     READY, DELIVERY,  FINISH
>         }
> ```
> 
> * EnumType.ORDINAL인 경우에 기존 DB의 OrderStatus 속성값의 2는 DELEVERY가 되어 큰 문제가 발생
> * **@Enumerated의 기본 값은 EnumType.ORDINAL이므로 반드시 EnumType.STRING으로 사용하자!**

- FINISH랑 DELIVERY 둘다 똑같은 OrderStatus 속성값을 가지게 되니 나중에 속성값으로 enum 값을 빼올 때 엄청난 에러가 나겠군요..! 항상 Enum 사용할 때는 `@Enumerated(EnumType.STRING)` 으로 해야겠습니당~~ 😎
