### ISSUE TITLE
JPQL 컴파일 에러 잡는 여부 (feat . QueryDSL)

### ISSUE THREAD

**Issue by myway00** [PeerGroup-JavaSpringBoot/SpringBootStudy#86]
@yoon-youngjin 님께서 공유해주신 의문사항

# 1) @Query (JPQL)

![image](https://user-images.githubusercontent.com/76711238/165443063-c4b7527e-c3df-4d6e-8bc1-94c19b6bac95.png)
![image](https://user-images.githubusercontent.com/76711238/165443460-51ecd7ae-8997-42d6-aec7-4b60022425eb.png)

- where -> wheree 로 오타를 내더라도 단순 typo 에러로만 나타남, 컴파일 에러는 X (run 누르면 돌아감)

# 2) QueryDSL

![image](https://user-images.githubusercontent.com/76711238/165443216-78851da9-9cd1-4a07-bc26-31994114aabe.png)
![image](https://user-images.githubusercontent.com/76711238/165443420-729e3baf-2ea5-4b20-93a8-1792d4e9a920.png)

- compile 에러로 확실하게 나타내줌, run 누르면 안 돌아감

**Comment by yoon-youngjin** [comment]
감사합니다  : ) 
JPQL 사용하는 경우에 오타가 난 뒤에 run을 하면 서버가 안켜지나요?

**Comment by myway00** [comment]
서버가 잠깐 켜졌다가, 바로 쿼리 생산할 수 없다는 에러로 꺼져버리긴 합니다..! 😂 이걸 켜졌다고 봐야할까요..?? ㅋㅋㅋㅋ 애매하네욥 ..!! 

반면 QueryDSL 은 run 조차도 되지 않구요!!

결국 책에서 말씀 하신 것처럼 run 돌려보기 전까지는 JPQL은 에러가 났는지 여부를 알 수 없는 것은 확실하네요!

1) JPQL
1-1 ) Tomcat 구동까진 가능
![image](https://user-images.githubusercontent.com/76711238/165455120-4effb4c4-3b6d-4edb-aa35-86368b525f69.png)
1-2) 그렇지만 QuerySyntaxException 으로 종료돼버림
![image](https://user-images.githubusercontent.com/76711238/165456037-c1835fb9-d20e-4f8e-babc-fbb3187dad66.png)


2) QueryDSL - Run 실행 시 
![image](https://user-images.githubusercontent.com/76711238/165454605-c4524bec-6860-4421-bc70-94e83361f4eb.png)

**Comment by yoon-youngjin** [comment]
감사합니다 !!!
