### ISSUE TITLE
Spring Boot Devtools - Applitacion 자동 재시작(Automatic restart 설정)

### ISSUE THREAD

**Issue by hehahihang** [PeerGroup-JavaSpringBoot/SpringBootStudy#89]
P.115
Springboot Devtools 관련
compiler.automake.allow.when.app.running 항목이 registry 없는 경우 해결 방법 공유드립니다! 
**IDEA 2021.2버전 부터 해당 설정이 레지스트리에서 Advanced Setting으로 옮겨진 것으로 확인됩니다**

1. **Build Project automatically** 체크
![image](https://user-images.githubusercontent.com/57223501/166129731-8e5e8307-836d-4421-b909-2e2692c5127d.png)

File - Settings - Build, Execution, Deployment - Complier - Build Project automatically 체크

2. **Allow auto-make to start even if developed application is currently running** 체크
![image](https://user-images.githubusercontent.com/57223501/166129811-3fc17701-1820-437b-bee6-eb3b8ab805be.png)

윈도우
File - Setting - Advanced Settings - Allow auto-make to start even if developed application is currently running 체크 

(맥은 Preference)

1,2 두가지 설정을 완료하시면 됩니다!

**Comment by myway00** [comment]
이슈로 해결과정 친절하게 남겨주셔서 감사합니다! :)
